
    
        DROP DATABASE IF EXISTS PROCEDURE_DB;
        CREATE DATABASE PROCEDURE_DB;
    



    
        DROP DATABASE IF EXISTS EXECUTE_DB;
        CREATE DATABASE EXECUTE_DB;
    



    
        DROP DATABASE IF EXISTS BATCH_EXECUTE_DB;
        CREATE DATABASE BATCH_EXECUTE_DB;
    



    
        DROP DATABASE IF EXISTS QUERY_DB;
        CREATE DATABASE QUERY_DB;
    



    
        DROP DATABASE IF EXISTS CONNECT_DB;
        CREATE DATABASE CONNECT_DB;
    



    
        DROP DATABASE IF EXISTS LOCAL_TRANSACTION;
        CREATE DATABASE LOCAL_TRANSACTION;
    



    
        DROP DATABASE IF EXISTS POOL_DB_1;
        CREATE DATABASE POOL_DB_1;
    



    
        DROP DATABASE IF EXISTS POOL_DB_2;
        CREATE DATABASE POOL_DB_2;
    



    
        DROP DATABASE IF EXISTS BASIC_EXECUTE_DB;
        CREATE DATABASE BASIC_EXECUTE_DB;
    



    
        DROP DATABASE IF EXISTS SIMPLE_QUERY_PARAMS_DB;
        CREATE DATABASE SIMPLE_QUERY_PARAMS_DB;
    



    
        DROP DATABASE IF EXISTS FUNCTION_DB;
        CREATE DATABASE FUNCTION_DB;
    

