[package]
org = "ballerinax"
name = "postgresql"
version = "0.1.0"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-0.1.0.jar"
groupId = "org.ballerinalang"
artifactId = "postgresql-native"
version = "0.1.0"


[[platform.java11.dependency]]
path = "@project.path@/repo/bala/ballerina/sql/@stdlib.sql.version@/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@"


[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.18.jar"
artafactId = "postgresql-connector-java"
groupId = "postgresql"
scope = "testOnly"
version = "42.2.18."
