[package]
org = "ballerinax"
name = "postgresql"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "sql"
version = "@stdlib.sql.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mysql-native"
version = "@project.version@"


[[platform.java11.dependency]]
path = "@project.path@/repo/balo/ballerina/sql/@stdlib.sql.version@/ballerina-sql-java11-0.5.3.balo"
# path = "@project.path@/repo/balo/ballerina/sql/@stdlib.sql.version@/platform/java11/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@"


[[platform.java11.dependency]]
path = "./lib/postgresql-connector-java-8.0.21.jar"
artafactId = "postgresql-connector-java"
groupId = "postgresql"
scope = "testOnly"
version = "8.0.17"
