[package]
org = "ballerinax"
name = "postgresql"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "sql"
version = "0.5.3"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.4"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.0.5"

[[dependency]]
org = "ballerina"
name = "config"
version = "1.0.5"

[[platform.java11.dependency]]
path = "../postgresql-native/build/libs/postgresql-native-0.1.0.jar"
groupId = "org.ballerinalang"
artifactId = "postgresql-native"
version = "0.1.0"


[[platform.java11.dependency]]
path = "/home/sasindu/Desktop/Important/Project/MyRepository/Code/module-ballerinax-postgresql/postgresql-ballerina/build/target/jballerina-tools-2.0.0-Preview8/repo/balo/ballerina/sql/0.5.3/platform/java11/sql-native-0.5.3.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "0.5.3"
# version = "0.5.4-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.18.jar"
artafactId = "postgresql-connector-java"
groupId = "postgresql"
# scope = "testOnly"
version = "42.2.18."

# [[platform.java11.dependency]]
# path = "../postgresql-native/lib/postgres-jdbc.jar"
# artafactId = "postgresql-jdbc"
# groupId = "postgresql"
# version = "42.2.18."
