CREATE USER connectUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO connectUser;

CREATE USER executeUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO executeUser;

CREATE USER queryUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO queryUser;

CREATE USER functionUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO functionUser;

CREATE USER procedureUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO procedureUser;

CREATE USER executeParamUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO executeParamUser;

CREATE USER simpleQueryUser WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE postgres TO simpleQueryUser;